# Generated by Django 4.0.3 on 2022-04-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filesharingapp', '0002_remove_file_filedata_file_filetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filetype',
            new_name='filetypedata',
        ),
    ]
